services:
  static_serve:
    image: ghcr.io/endikau/nd_site-static_serve:${ND_SITE_TAG:-latest}
    restart: unless-stopped
    ports:
      - "12348:8080"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
