---
title: "RAG-Wissensassistent für Regelwerke"
subtitle: "..."
figtitle: "🕸️"
draft: false
toc_show: true
execute:
  echo: false
  warning: false
  message: false
---

```{r}
ggplot2::theme_set(`+`(
  ggplot2::theme_minimal(base_size = 14, base_family = "Open Sans"),
  ggplot2::theme(
    axis.text.x = ggplot2::element_text(size = 12),
    axis.text.y = ggplot2::element_text(size = 12),
    axis.title.x = ggplot2::element_text(size = 14),
    axis.title.y = ggplot2::element_text(size = 14),
    title = ggplot2::element_text(size = 14),
    strip.text = ggplot2::element_text(size = 14),
    panel.grid.major = ggplot2::element_blank(),
    panel.grid.minor = ggplot2::element_blank(),
    panel.background = ggplot2::element_rect(fill = NA, colour = NA),
    plot.background = ggplot2::element_rect(fill = NA, colour = NA),
    legend.position = "bottom"
  )
))
```

```{r}
data_path <- here::here("content", "case_studies", "rag_system", "data")

rag_client <- nd.util::rag_client()

# fs::path(data_path, "datenblaetter") |>
#   fs::dir_ls() |>
#   purrr::walk(\(.path) {
#     rag_client$ingest_pdf_async(.pdf_paths = .path)
#   })

# rag_client$chat_stream("Worum geht es in dem Dokument?")
```

```{r}
#| output: asis
rag_client$system_prompt
```


```{r}
#| output: asis
rag_client$context_prompt
```


```{r}
#| output: asis
rag_client$condense_prompt
```


```{r}
#| output: asis
rag_client$response_prompt
```


```{r}
#| output: asis
rag_client$context_refine_prompt
```


```{r}
nd.util::nd_popover("hallo", )
```